### ISSUE TITLE
Fightcade fails to launch on archlinux

### ISSUE THREAD

**Issue by Xenphor** [poliva/pyqtggpo#20]
I get this error:
```
$ ./fightcade 
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from ggpo.common.controller import Controller
  File "/home/user/Downloads/FightCade/ggpo/common/controller.py", line 585
    if self.username == p1:
                          ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by yosmikey** [comment]
I have the same problem. I never did get the Linux FightCade client working on ArchLinux. I just use the Windows client in wine although just be aware that the client doesn't close properly, so you'll have to kill some PIDs. Hopefully someone finds a fix for the native linux client on non-ubuntu based distros.

**Comment by poliva** [comment]
will be fixed in next release, meanwhile you can replace tabs with 4 spaces in ``ggpo/common/controller.py``.

**Comment by poliva** [comment]
ok, i have installed archlinux to see what's failing. Archlinux uses python3 by default but fightcade needs python2 so for fightcade to work, the first line of main.py and ggpfoba.py needs to be changed to "env python2" instead of "env python". I'll make sure the next version works out of the box on Archlinux.
