### ISSUE TITLE
NAT Traversal Bug

### ISSUE THREAD

**Issue by kevinlc43** [poliva/pyqtggpo#44]
Looks like FightCade is having problems doing NAT traversal on your connection. If you can't connect try opening GGPO ports on your router (6000 to 6009 udp). 
How to FIx IT??

**Comment by poliva** [comment]
forward ggpo ports, or challenge people who have them open (you can see the ping value next to their name in the player's list).

**Comment by ner00** [comment]
Just for the sake of it, I'm going to reinforce that this "bug"was never solved.
Forwarding ports 6000-6009/UDP was never enough for a lot of people, at best it works by enabling DMZ. This is possibly tied to router make and/or model, because a lot of people can play it (even without forwarding said ports) which kind of points that port forwarding is a sign of shortcomings in UPnP/NAT implementation (firmware, software or both).

**Comment by kevinlc43** [comment]
what is DMZ?????

**Comment by ner00** [comment]
https://en.wikipedia.org/wiki/DMZ_(computing)
Refer to the *DMZ Host* paragraph.

It's a function that most routers have which allow an IP address inside the local network to receive all traffic coming from the internet without having to care about port forwarding or firewall (usually DMZ is just a bypass to the standard firewalling). It is also extremely unsafe since the machine to which DMZ is enabled has all it's services become available to the internet if there is not another additional layer of protection (Windows Firewall, etc).

**Comment by kevinlc43** [comment]
THANK YOU VERY MUCH❤❤❤

**Comment by kevinlc43** [comment]
Thank You very much❤❤
