### ISSUE TITLE
[FIGHTCADE] Can't play any games : /

### ISSUE THREAD

**Issue by OrageSpark** [poliva/pyqtggpo#67]
Hello !
The title says it all... I wanted to enjoy some Marvel Super Heroes vs Street Fighter, but when I launch any game, FC just doesn't do anything, it doesn't even show me an error message...
Could someone help me, please ?

**Comment by lmack82** [comment]
I've actually had the same problem recently. It used to work fine all the time and then sometime around the end of last year, it refused to function any longer.

What happens is Fightcade doesn't launch the FBA emulator any longer. No window pops up. If you try to spectate, you get nothing. If you try to accept a challenge or type in "/play" to launch it yourself, it'll say "Launching (romsetnamehere)" in the chat area, but nothing actually opens or happens at all. Doesn't matter what game. As the OP said, there aren't any error messages at all. I know I'm not missing any files either because it used to work fine and I've changed nothing between it working and not working.

I've also tried deleting all of Fightcade's files, re-downloading it, and setting it up again to see my ROM folder. No change.

**Comment by OrageSpark** [comment]
Actually, I only had to move FC to another folder and everything worked like it used to work before... thanks for the reply anyway !

**Comment by lmack82** [comment]
I wish that worked for me. I tried moving the folder around, but that didn't help anything.

**Comment by OrageSpark** [comment]
Sorry for you, buddy : /
